coordinators:
  7930978: Ирина Рыбакова
  7998125: Настя Рябова
  7834874: Ольга Самойлова
  8772068: Елена Левина
  6151878: Виктория Пятыгина
  7906436: Варвара Бутковская
  8366269: Наталья Збеглова
  7148627: Максим Зайкин
  8232264: Полина Савченко
  8557079: Елена Безрученкова
  8187353: Александр Нестеров
  8881338: Евгений Синякин
  8281784: Елена Максимова
  8242201: Евгения Аникина
  7183929: Асия Яблочкова
  8453121: Ксения Райская
  7985503: Анна Суханова
  8620712: Дияз Сейфетдинов
  8078713: Олег Гежин
  5810125: Ольга Соболева
  7150186: Росина Савицкая
  7183936: Елена Зайцева
  7864914: Нурлан Асанбеков
lead_coordinators_to_profession:
  Ирина Панина:
  - da
  - dau
  - deg
  Виктория Пятыгина:
  - pydp
  - ds
  - dsu
  - aml
  - dll
  Евгения Сергеева:
  - an
  - shan
  - jd
  - shjd
  - cpp
  - cppqt
  - cppiot
  - cpppue
  Элионора Петрова:
  - qa
  - qamid
  - qapy
  - qamidpy
  - shqa
  - ios
  - go
  - golpro
  Анастасия Трещина:
  - shdevops
  - sys
  - fops
  - abi
  - abu
  - dmar
  - pbi
  - pdx
  - ban
  - banpro
  Мария Пескова:
  - sal
  - pal
  - awh
  - sup
  - sql
  - sqlp
  Оксана Махонина:
  - spd
  - pd
  - fpy
  Наталья Нагаева:
  - onec
  - onecmid
  - git
  - sib
  Юлия Похвищева:
  - ntw
  - pae
  Алёна Хохлова:
  - shfe
  - fe
  - fsmid
  - fsmidjs
  - fsmidpd
  - btrx
  - btrxpro
  Денис Кобин:
  - oca
  - ocamid1
